### PR TITLE
Add a git-ignore file

### PR DESCRIPTION
**Pull request by jdb78**

### CODE REVIEW

**Comment by johnyf** [comment]
As a note, the file `.gitignore` added by this pull request appears to be based on the file https://github.com/github/gitignore/blob/218a941be92679ce67d0484547e3e142b2f5f6f0/Python.gitignore, which is licensed under the CC0 Public Domain Dedication, thus it can be included in the GPL licensed repository.

**Review by Technologicat — APPROVED** [review]
LGTM. That's a very comprehensive `.gitignore`!

**Comment by Technologicat** [comment]
@johnyf , maybe we could add a comment with a link to the original at the top of the file?

**Comment by jdb78** [comment]
Added link

**Comment by johnyf** [comment]
Yes, that sounds good. Thanks for adding the link.

**Pull request merged**
